version: '3.8'

services:
  # Frontend application (Nuxt.js)
  frontend:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    container_name: solutech_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - solutech_network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    container_name: solutech_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: events_central
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Server@2244
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - solutech_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Laravel backend
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: solutech_backend
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: events_central
      DB_USERNAME: postgres
      DB_PASSWORD: Server@2244
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database
      CACHE_DRIVER: database
      CENTRAL_URL: http://localhost:8000
      HOST_URL: localhost
    volumes:
      - ./laravel:/var/www/html
      - laravel_vendor:/var/www/html/vendor
      - laravel_node_modules:/var/www/html/node_modules
      - laravel_storage:/var/www/html/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - solutech_network

  # Nginx web server for Laravel
  api:
    image: nginx:alpine
    container_name: solutech_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - solutech_network

networks:
  solutech_network:
    driver: bridge

volumes:
  postgres_data:
  laravel_vendor:
  laravel_node_modules:
  laravel_storage:
